MyWebCoreApp_Client/Models/ErrorViewModel.cs
namespace MyWebCoreApp_Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyWebCoreApp_Client/Controllers/ConvertController.cs
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Text;
using MyWebCoreApp_Client.Models;

namespace MyWebCoreApp_Client.Controllers
{
    
    public class ConvertController : Controller
    {
        // URL des Servers
        private static string url = "http://localhost:5000/api/convert";

        private readonly HttpClient httpClient;

        public ConvertController()
        {
            httpClient = new HttpClient();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConvertToWords(string amount)
        {
            // Daten vorbereiten
            var requestData = new StringContent(amount, Encoding.UTF8, "text/plain");

            // Anfrage an den Server senden
            var response = await httpClient.PostAsync(url, requestData);

            if (response.IsSuccessStatusCode)
            {
                // Antwort des Servers lesen
                string result = await response.Content.ReadAsStringAsync();
                ViewBag.Result = result;
            }
            else
            {
                ViewBag.Result = "Error";
            }

            ViewBag.Amount = amount;

            //return View("Index");

            return View("~/Views/Home/Index.cshtml");

        }


    }
}

MyWebCoreApp_Client/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebCoreApp_Client.Models;
using System.Diagnostics;

namespace MyWebCoreApp_Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyWebCoreApp_Client/Views/Home/Index.cshtml
@*@{
    ViewData["Title"] = "ClientWebApp";
}

<div class="text-center">
    <h1 class="display-4">Currency (dollars) from numbers into words converter</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@

@model decimal

@{
    ViewData["Title"] = "ClientWebApp";
    string result = ViewBag.Result ?? "";
    string amount = ViewBag.Amount ?? "";
}

<div class="text-center">
    <h1 class="display-4">Currency (dollars) from numbers into words converter</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="post" asp-controller="Convert" asp-action="ConvertToWords">
                <div class="form-group">
                    <label for="amount">Enter the amount in dollars:</label>
                    <input type="text" class="form-control" id="amount" name="amount" value="@amount" required>
                </div>
                <p></p>
                <button type="submit" class="btn btn-primary">Convert</button>
            </form>
            <div>
                @if (!string.IsNullOrEmpty(result))
                {
                    <br />
                    @if (result.StartsWith("Error:"))
                    {
                        <h4>
                            <span style="color: red;">Error:</span>
                        </h4>
                        <p style="color: red">@result.Substring(6)</p>
                        
                    }
                    else
                    {
                        <h4>
                            <span>Result:</span>
                        </h4>
                        <p>@result</p>
                    }
                }
            </div>
        </div>
    </div>

    @if (Model != decimal.Zero)
    {
        <div class="row mt-4">
            <div class="col-md-6 offset-md-3">
                <h4>Result:</h4>
                <p>@Model.ToString("C") in words is: @result</p>
            </div>
        </div>
    }
</div>

MyWebCoreApp_Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyWebCoreApp_Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyWebCoreApp_Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyWebCoreApp_Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyWebCoreApp_Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>